version: '3.8'

# Development Docker Compose Override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api:
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - MODE=development
    ports:
      - "8000:8000"  # Expose port for direct access

  workers:
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
    command: ["uv", "run", "dramatiq", "app.tasks.background_tasks", "--watch", "app", "--processes", "1", "--threads", "2"]

  redis:
    ports:
      - "6379:6379"  # Expose Redis port for development tools

  mongodb:
    ports:
      - "27017:27017"  # Expose MongoDB port for development tools
    environment:
      # Simpler auth for development
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password